// Benchmark mirroring src/composables/ai.ts
const G=20,N=400,DX=[0,1,0,-1],DY=[-1,0,1,0];
const DIR_MAP={up:{x:0,y:-1},right:{x:1,y:0},down:{x:0,y:1},left:{x:-1,y:0}};
const deadly=new Uint8Array(N),deadly2=new Uint8Array(N),vis=new Uint8Array(N),prev=new Int32Array(N),q=new Int32Array(N);
const cell=(x,y)=>y*G+x,inGrid=(x,y)=>x>=0&&x<G&&y>=0&&y<G;
const dirOf=(f,t)=>t.y<f.y?'up':t.x>f.x?'right':t.y>f.y?'down':'left';
const copySnake=s=>s.map(p=>({x:p.x,y:p.y}));
function fillDeadly(snake,obstacles,frozen,buf){buf.fill(0);const end=frozen?snake.length:snake.length-1;for(let i=0;i<end;i++)buf[cell(snake[i].x,snake[i].y)]=1;for(const o of obstacles)buf[cell(o.x,o.y)]=1;}
function legal(snake,obstacles,frozen){fillDeadly(snake,obstacles,frozen,deadly);const h=snake[0];const neck=snake.length>1?snake[1]:null;const out=[];for(let d=0;d<4;d++){const nx=h.x+DX[d],ny=h.y+DY[d];if(!inGrid(nx,ny))continue;if(neck&&nx===neck.x&&ny===neck.y)continue;if(deadly[cell(nx,ny)])continue;out.push({x:nx,y:ny});}return out;}
function flood(buf,sx,sy){const s=cell(sx,sy);if(buf[s])return 0;vis.fill(0);let head=0,tail=0;vis[s]=1;q[tail++]=s;let count=1;while(head<tail){const cur=q[head++];const cx=cur%G,cy=(cur/G)|0;for(let d=0;d<4;d++){const nx=cx+DX[d],ny=cy+DY[d];if(!inGrid(nx,ny))continue;const ni=cell(nx,ny);if(vis[ni]||buf[ni])continue;vis[ni]=1;q[tail++]=ni;count++;}}return count;}
function bfs(buf,start,target,targetOpen){const si=cell(start.x,start.y),ti=cell(target.x,target.y);if(si===ti)return[];prev.fill(-1);vis.fill(0);let head=0,tail=0;vis[si]=1;q[tail++]=si;const saved=buf[ti];if(targetOpen)buf[ti]=0;while(head<tail){const cur=q[head++];if(cur===ti)break;const cx=cur%G,cy=(cur/G)|0;for(let d=0;d<4;d++){const nx=cx+DX[d],ny=cy+DY[d];if(!inGrid(nx,ny))continue;const ni=cell(nx,ny);if(vis[ni]||buf[ni])continue;vis[ni]=1;prev[ni]=cur;q[tail++]=ni;}}if(targetOpen)buf[ti]=saved;if(!vis[ti])return null;const path=[];let cur=ti;while(cur!==si){path.push({x:cur%G,y:(cur/G)|0});cur=prev[cur];}path.reverse();return path;}
function prepSearch(snake,obstacles,frozen,buf){fillDeadly(snake,obstacles,frozen,buf);const h=snake[0],t=snake[snake.length-1];buf[cell(h.x,h.y)]=0;if(!frozen)buf[cell(t.x,t.y)]=0;return{head:h,tail:t};}
function reachTail(snake,obstacles,frozen){const {head,tail}=prepSearch(snake,obstacles,frozen,deadly);return bfs(deadly,head,tail,true)!==null;}
function spaceOf(snake,obstacles,frozen){const {head}=prepSearch(snake,obstacles,frozen,deadly);return flood(deadly,head.x,head.y);}
function tailPathLen(snake,obstacles,frozen){const {head,tail}=prepSearch(snake,obstacles,frozen,deadly);const p=bfs(deadly,head,tail,true);return p?p.length:-1;}
function advance(snake,food,frozen,next){const ns=copySnake(snake);ns.unshift({x:next.x,y:next.y});const ate=next.x===food.x&&next.y===food.y;if(!ate)ns.pop();return{snake:ns,frozen:ate,ate};}
function safeFoodFirst(snake,food,obstacles,frozen){const {head}=prepSearch(snake,obstacles,frozen,deadly);const path=bfs(deadly,head,food,false);if(!path||!path.length)return null;let s=copySnake(snake),fr=frozen;for(let i=0;i<path.length;i++){const r=advance(s,food,fr,path[i]);s=r.snake;fr=r.frozen;if(!reachTail(s,obstacles,fr)){if(!(r.ate&&spaceOf(s,obstacles,fr)>=s.length+12))return null;}}if(!fr)return null;if(snake.length>=100){const sp=spaceOf(s,obstacles,fr);if(sp<Math.floor(snake.length*0.3))return null;}return path[0];}
function evaluate(snake,food,obstacles,frozen,ate){const len=snake.length;const rt=reachTail(snake,obstacles,frozen);const space=spaceOf(snake,obstacles,frozen);const tpl=tailPathLen(snake,obstacles,frozen);const moves=legal(snake,obstacles,frozen);if(!rt&&space<len+12)return -1e12;let score=0;if(rt)score+=5e6+Math.max(tpl,0)*800;else score-=2e6;score+=space*400;score+=moves.length*5000;const h=snake[0];const fd=Math.abs(h.x-food.x)+Math.abs(h.y-food.y);if(rt&&space>len*2&&moves.length>=2)score-=fd*90;else if(rt&&space>len*1.3)score-=fd*25;else score-=fd*3;if(moves.length<=1)score-=8e4;if(space<len+3)score-=1e5;if(ate)score+=rt?25e3:-3e6;let kids=0;for(const m of moves){const r=advance(snake,food,frozen,m);if(reachTail(r.snake,obstacles,r.frozen))kids++;}score+=kids*8000;return score;}
function findSafeDirection(snake,food,obstacles,tailFrozen){if(!snake.length)return'right';const head=snake[0];const moves=legal(snake,obstacles,tailFrozen);if(!moves.length)return'right';const foodStep=safeFoodFirst(snake,food,obstacles,tailFrozen);if(foodStep)return dirOf(head,foodStep);const keep=moves.filter(m=>{const r=advance(snake,food,tailFrozen,m);return reachTail(r.snake,obstacles,r.frozen);});const pool=keep.length?keep:moves;let best=pool[0],bestScore=-Infinity;for(const m of pool){const r=advance(snake,food,tailFrozen,m);const sc=evaluate(r.snake,food,obstacles,r.frozen,r.ate);if(sc>bestScore){bestScore=sc;best=m;}}if(!keep.length){const {head:h,tail}=prepSearch(snake,obstacles,tailFrozen,deadly2);const tp=bfs(deadly2,h,tail,true);if(tp&&tp.length){const step0=tp[0];if(moves.some(m=>m.x===step0.x&&m.y===step0.y))return dirOf(head,step0);}}return dirOf(head,best);}
function spawnFood(snake,obstacles){for(let a=0;a<500;a++){const pos={x:Math.floor(Math.random()*G),y:Math.floor(Math.random()*G)};if(snake.some(s=>s.x===pos.x&&s.y===pos.y))continue;if(obstacles.some(o=>o.x===pos.x&&o.y===pos.y))continue;return pos;}return{x:0,y:0};}
function generateObstacles(snake,count=8){const obstacles=[];while(obstacles.length<count){const pos={x:Math.floor(Math.random()*G),y:Math.floor(Math.random()*G)};if(snake.some(s=>s.x===pos.x&&s.y===pos.y))continue;if(obstacles.some(o=>o.x===pos.x&&o.y===pos.y))continue;if(Math.abs(pos.x-10)+Math.abs(pos.y-10)<4)continue;obstacles.push(pos);}return obstacles;}
function runOne(maxMoves=12000){let snake=[{x:10,y:10},{x:9,y:10},{x:8,y:10}];const obstacles=generateObstacles(snake,8);let food=spawnFood(snake,obstacles);let score=0,tailFrozen=false;for(let move=0;move<maxMoves;move++){const dir=findSafeDirection(snake,food,obstacles,tailFrozen);const d=DIR_MAP[dir];const head={x:snake[0].x+d.x,y:snake[0].y+d.y};if(!inGrid(head.x,head.y))return{score,length:snake.length,dead:'wall'};if(obstacles.some(o=>o.x===head.x&&o.y===head.y))return{score,length:snake.length,dead:'obstacle'};if(snake.some((s,i)=>{if(i===0)return false;if(i===snake.length-1&&!tailFrozen)return false;return s.x===head.x&&s.y===head.y;}))return{score,length:snake.length,dead:'self'};const ate=head.x===food.x&&head.y===food.y;snake.unshift(head);if(ate){score+=10;tailFrozen=true;food=spawnFood(snake,obstacles);}else{snake.pop();tailFrozen=false;}if(snake.length+obstacles.length>=N-2)return{score,length:snake.length,dead:'win'};}return{score,length:snake.length,dead:'timeout'};}
const RUNS=Number(process.argv[2])||30;
const scores=[],deaths={};const t0=Date.now();
for(let i=0;i<RUNS;i++){const r=runOne();scores.push(r.score);deaths[r.dead]=(deaths[r.dead]|0)+1;if((i+1)%10===0)console.error(`p ${i+1}/${RUNS} avg=${(scores.reduce((a,b)=>a+b,0)/(i+1)).toFixed(0)}`);}
scores.sort((a,b)=>a-b);const avg=scores.reduce((a,b)=>a+b,0)/RUNS;
console.log(`=== ${RUNS} runs ${Date.now()-t0}ms ===`);
console.log(`Avg ${avg.toFixed(1)} Med ${scores[RUNS>>1]} Min ${scores[0]} Max ${scores[RUNS-1]}`);
console.log('Deaths',deaths);
if(avg>=2500)console.log('PASS strong');
else if(avg>=1500)console.log('PASS');
else if(avg>=1200)console.log('IMPROVED');
else console.log('FAIL');
